# Generated by Django 4.2.4 on 2023-09-05 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(max_length=50, verbose_name='Nombre de Ciudad')),
                ('estado', models.CharField(max_length=10, verbose_name='Estado')),
            ],
        ),
    ]
