# Generated by Django 4.2.4 on 2023-09-06 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_ciudad_short_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciudad',
            options={'ordering': ['Descripcion'], 'verbose_name': 'Tabla Ciudad', 'verbose_name_plural': 'Registro de ciudades'},
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo'), ('B', 'Bloqueado')], max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterUniqueTogether(
            name='ciudad',
            unique_together={('Descripcion', 'short_name')},
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50, verbose_name='Nombre de la persona')),
                ('Apellido', models.CharField(max_length=50, verbose_name='Apellido de la persona')),
                ('FechaNacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('Celular', models.CharField(max_length=20, verbose_name='Celular')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ciudad')),
            ],
        ),
    ]
