# Generated by Django 4.2.4 on 2023-09-07 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_ciudad_options_alter_ciudad_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidad', models.CharField(max_length=30, verbose_name='Habilidad')),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='habilidades',
            field=models.ManyToManyField(to='home.habilidades'),
        ),
    ]
