# Generated by Django 4.2.4 on 2023-09-10 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('Apellido', models.CharField(max_length=30, verbose_name='Apellido')),
                ('TipoDocumento', models.CharField(choices=[('CI', 'Cedula de Identidad'), ('pasaporte', 'Pasaporte')], max_length=30, verbose_name='Tipo de Documento')),
                ('NroDocumento', models.CharField(max_length=15, verbose_name='N˚ de Documento')),
                ('Celular', models.CharField(max_length=20, verbose_name='N˚ de Celular')),
                ('Email', models.CharField(max_length=50, verbose_name='Email')),
                ('Direccion', models.CharField(max_length=30, verbose_name='Direccion')),
                ('Estado', models.CharField(choices=[('Activo', 'Cedula de Identidad'), ('Eliminado', 'Pasaporte'), ('Bloqueado', 'Bloqueado'), ('Suspendido', 'Suspendido')], max_length=10, verbose_name='Estado')),
            ],
        ),
    ]
